name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn' # Buildi sürətləndirmək üçün keşləmə

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile # Daha stabil install üçün

      - name: Debug - List Files
        run: ls -R # Harda olduğumuzu və android qovluğunu görmək üçün

      -       - name: Build APK
        run: |
          # Sənin Android qovluğun böyük ehtimalla 'client' içindədir
          cd client
          chmod +x ./gradlew
          ./gradlew assembleDebug
            else
            echo "XƏTA: android qovluğu tapılmadı! Zəhmət olmasa proyekt strukturunu yoxla."
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SAMP-Launcher-APK
          path: "**/build/outputs/apk/debug/*.apk" # Daha geniş axtarış yolu